# Generated by Django 4.2.4 on 2023-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.auctionlistings'),
        ),
    ]
