# Generated by Django 4.2.4 on 2023-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='url_picture',
            field=models.CharField(max_length=100),
        ),
    ]
