# Generated by Django 4.2.5 on 2023-09-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='post_date',
        ),
    ]
