# Generated by Django 4.2.4 on 2023-09-30 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlistings_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='date_of_post',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
