# Generated by Django 4.2.4 on 2023-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('NO_CAT', 'No category'), ('FUR', 'Furniture'), ('COM', 'Computer'), ('COM_AS', 'Computer Accessories'), ('TS', 'Toys'), ('GRD_UTIL', 'Garden Utilities')], default='NO_CAT', max_length=100),
        ),
    ]
